modLoader="javafml"
loaderVersion="[47,)"
license="Custom license"

[[mods]]
modId="puresmores"
version="1.1.0"
displayName="Pure S'mores"
credits="purejosh"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/puresmores"
logoFile="logo.png"
authors="purejosh"
description="Enjoy delicious s'mores next to a campfire with your friends!"

[[dependencies.puresmores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




